name: Continous Builds

on:
  push:
    branches: [master]

env:
  VERSION: v6.4.0
  QT_VERSION: 6.7.0
  QTIFW_VERSION: 4.7

jobs:
  job_2:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: install qt6
        run: |
          pip install aqtinstall
          python3 -m aqt install-qt -O ${{ github.workspace }}/Qt/ windows desktop ${{ env.QT_VERSION }} win64_msvc2019_64
          python3 -m aqt install-tool -O ${{ github.workspace }}/Qt/ windows desktop tools_ifw
          echo "${{ github.workspace }}/Qt/${{ env.QT_VERSION }}/msvc2019_64/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
          echo "${{ github.workspace }}/Qt/Tools/QtInstallerFramework/${{ env.QTIFW_VERSION }}/bin/" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - name: build
        shell: cmd
        run: |
          choco install wget --no-progress
          cd .\FastTrack\packages\FastTrack\data
          rm placeholder
          wget https://github.com/FastTrackOrg/FastTrack/releases/download/${{ env.VERSION }}/FastTrack.zip
          7z x FastTrack.zip -y
          rm FastTrack.zip
          7z a data.7z * -sdel
          cd ${{ github.workspace }}
          repogen.exe -p .\FastTrack\packages FastTrackRep
          binarycreator.exe -p .\FastTrack\packages -c .\FastTrack\config\config.xml FastTrackInstaller
      - name: Windows artefact
        uses: actions/upload-artifact@v4
        with:
          name: FastTrackInstaller
          path: ./FastTrackInstaller.exe
      - name: Windows artefact
        uses: actions/upload-artifact@v4
        with:
          name: FastTrackRep
          path: ./FastTrackRep
